Module2 task1
htmlacademy-adaptive/2145863-mishka-27 pull request #2
Opened 2022-11-27 21:51 UTC by gitalexus

Привет! 
Заверстал, пока кривовато наверное.
Не стал долго думать над БЭМ классами, все равно пока общая картина не видна и все будет менятся.

2022-11-29 08:49 UTC, Kartaviy-arteom requested changes

2022-11-29 08:49 UTC, Kartaviy-arteom commented on source/catalog.html
> +    <link rel="icon" href="favicon.png">
закинь ее к картинкам, а в корне у тебя будет ico

2022-11-29 08:49 UTC, Kartaviy-arteom commented on source/form.html
> +      <a class="main-nav__logo" href="index.html">
тут элемент без блока. Элемент должен принадлежать блоку

2022-11-29 08:49 UTC, Kartaviy-arteom commented on source/form.html
> +                <path opacity=".2"
прозрачность указаная инлайново будет тебе только мешать при оформлении состояний.

2022-11-29 08:49 UTC, Kartaviy-arteom commented on source/index.html
> +        <h2 class="visually-hidden">Презентация</h2>
я не увидел h1 на странице

2022-11-29 08:49 UTC, Kartaviy-arteom commented on source/index.html
> +      </section>
возможно эти две секции можно объединить, возможна одна будет включать в себя другую.
Обрати внимание как это выглядит на соседних макетах для других разрешений

2022-11-29 08:49 UTC, Kartaviy-arteom commented on source/index.html
> +              <p class="reviews__tag">@misssssiskras</p>
я бы добавил ссылку, похоже на ссылку на профиль в соц сетях или что-то такое

2022-11-29 08:49 UTC, Kartaviy-arteom commented on source/index.html
> +              <p class="reviews__author">Анастасия Красильникова</p>
использование параграфа для одного двух слов выглядит как-то избыточно.
Здесь кстати неплохо ложится блок цитаты. У тебя есть цитата и есть ее автор

2022-11-29 08:49 UTC, Kartaviy-arteom commented on source/index.html
> +            <dd class="contacts__text contacts__text--email">info@mimimishkashop.ru</dd>
ссылка на email

2022-11-29 08:49 UTC, Kartaviy-arteom commented on source/form.html
> +        <form class="order__form" action="https://echo.htmlacademy.ru" method="post">
обрати, пожалуйста, внимание, некоторые поля у формы обязательны к заполнению и это можно указать средствами html

2022-11-29 08:49 UTC, Kartaviy-arteom commented on source/form.html
> +            <input class="control--phone" type="text" name="phone" placeholder="+7 ХХХ ХХХ ХХ ХХ*">
label  для полей форм

2022-11-29 12:56 UTC, gitalexus commented on source/form.html
> +            <input class="control--phone" type="text" name="phone" placeholder="+7 ХХХ ХХХ ХХ ХХ*">
Здесь всего по одному элементу в филдсете и сам филдсет содержит назавние для этого инпута.
Если я вставлю label тогда мне придется их скрыть. В этом есть смысл? Читалка филдсет прочитает так же вроде бы.
Или мне лучше добавить lable и убрать fildset, чтобы не было дублирования? Я их оставил в рамках единого оформления полей формы.

2022-11-30 06:14 UTC, Kartaviy-arteom approved these changes

2022-11-30 06:14 UTC, merged